# Generated by Django 5.0.3 on 2024-03-31 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "verbose_name": "Изоброжение",
                "verbose_name_plural": "Изоброжения",
            },
        ),
        migrations.RemoveField(
            model_name="image",
            name="url",
        ),
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(
                default="", upload_to="shop_images/", verbose_name="Изоброжение"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="image",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="products",
                to="products.category",
                verbose_name="Категории",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shops",
                to="products.product",
                verbose_name="Продукт",
            ),
        ),
    ]
