# Generated by Django 5.0.3 on 2024-03-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_image_options_remove_image_url_image_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="image_url",
        ),
        migrations.AddField(
            model_name="image",
            name="url",
            field=models.CharField(
                default="", max_length=2048, verbose_name="Ссылка на изоброжение"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shop",
            name="image",
            field=models.ImageField(
                default="", upload_to="shop_images/", verbose_name="Изоброжение"
            ),
            preserve_default=False,
        ),
    ]
