# Generated by Django 5.0.3 on 2024-03-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0003_remove_image_image_remove_shop_image_url_image_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ManyToManyField(
                blank=True, related_name="children", to="products.category"
            ),
        ),
    ]
